---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: install plugin analysis-icu
  elasticsearch_plugin:
    name: analysis-icu
    state: "{{ elasticsearch_package_state }}"

- name: create elasticsearch directories if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: elasticsearch
    group: elasticsearch
  with_items: 
    - "{{ elasticsearch_data }}"
    - "{{ elasticsearch_logs }}"
    
- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch

- name: Force a restart if configuration has changed.
  meta: flush_handlers

- name: Start Elasticsearch.
  service:
    name: elasticsearch
    state: "{{ elasticsearch_service_state }}"
    enabled: "{{ elasticsearch_service_enabled }}"

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
