---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - elasticsearch

- name: install plugin analysis-icu
  elasticsearch_plugin:
    name: analysis-icu
    state: "{{ elasticsearch_package_state }}"
  tags:
    - elasticsearch

- name: create elasticsearch directories if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: elasticsearch
    group: elasticsearch
  with_items:
    - "{{ elasticsearch_data }}"
    - "{{ elasticsearch_logs }}"
  tags:
    - elasticsearch

- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch
  tags:
    - elasticsearch

- name: configure elasticsearch jvm options.
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ elasticsearch_jvm }}"
  notify: restart elasticsearch
  tags:
    - elasticsearch

- name: configure elasticsearch loggin level.
  lineinfile:
    dest: /etc/elasticsearch/log4j2.properties
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ elasticsearch_logger_config }}"
  notify: restart elasticsearch
  tags:
    - elasticsearch

- name: Set limits.conf
  pam_limits:
    domain: elasticsearch
    limit_type: "-"
    limit_item: nofile
    value: "65535"

- name: Set virtual memory
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present

- name: Force a restart if configuration has changed.
  meta: flush_handlers
  tags:
    - elasticsearch

- name: Start Elasticsearch.
  service:
    name: elasticsearch
    state: "{{ elasticsearch_service_state }}"
    enabled: "{{ elasticsearch_service_enabled }}"
  tags:
    - elasticsearch

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
  tags:
    - elasticsearch

- name: set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0755
  when: java_home is defined and java_home
  notify: restart elasticsearch
  tags:
    - elasticsearch
