---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: jeduoliveira.zulu_openjdk
    - role: jeduoliveira.elasticsearch

  post_tasks:
    - name: Check if tomcat is running.
      uri:
        url: "http://127.0.0.1:8080/"
